export default  {
    USER_REGISTER: 'USER_REGISTER',
    START_LOAD: '_START_LOAD',
    FINISH_LOAD: '_FINISH_LOAD',
    GET_ERRORS: 'GET_ERRORS',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILES: 'GET_PROFILES',
    CLEAR_PROFILE: 'CLEAR_PROFILE',   

}